import { SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AdminSidebar } from "@/features/admin/overview/components/Sidebar";
import { Separator } from "@/components/ui/separator";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <AdminSidebar />
      <div className="w-full px-3">
        <div className="py-4 flex flex-row justify-between">
            <SidebarTrigger />
        </div>
        <Separator />
        <div className="py-4">{children}</div>
      </div>
    </>
  );
}

